# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-02-28 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_auto_20190228_1447'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='image',
            name='description',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='image_url',
            field=models.CharField(max_length=1200, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='uploaded_by',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
