# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-03-02 09:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_auto_20190228_1500'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image_url',
            new_name='img_url',
        ),
        migrations.AddField(
            model_name='image',
            name='img_id',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
