# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-03-02 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_auto_20190302_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='img_url',
            field=models.ImageField(max_length=1200, null=True, upload_to=''),
        ),
    ]
