# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-03-02 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0007_auto_20190302_1038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='img_id',
        ),
        migrations.AddField(
            model_name='image',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
